require:
  - rubocop-rails
  - rubocop-rspec

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false